# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-local/all.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  # renovate: datasource=github-releases depName=argo-cd packageName=argoproj/argo-cd
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.13.4/manifests/install.yaml
  - namespace.yaml

patches:
  - path: argocd-server.yaml

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - kustomize.buildOptions="--enable-alpha-plugins --enable-exec"
      # WEB UI でターミナルを実行できるようにする
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/web_based_terminal/
      - exec.enabled=true
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure=true
