# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-local/all.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  # renovate: datasource=github-releases depName=argo-cd packageName=argoproj/argo-cd
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - namespace.yaml
  - secret.yaml

labels:
  - includeSelectors: true
    pairs:
      env: production

configMapGenerator:
  - behavior: merge
    literals:
      - kustomize.buildOptions=--enable-helm
    name: argocd-cm
