apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.6.7

patches:
  - path: argocd-cmd-params-cm.yaml
  - target:
      kind: Service
      name: argocd-server
    patch: |-
      - op: remove
        path: /spec/ports/0/targetPort
      - op: remove
        path: /spec/ports/1/targetPort