# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-local/all.json
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    name: argocd
