apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpbin-deployment
  labels:
    app: httpbin
    app.kubernetes.io/component: server
    app.kubernetes.io/version: latest
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: httpbin
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: httpbin
    spec:
      containers:
      - name: httpbin
        image: kennethreitz/httpbin:latest
        ports:
        - containerPort: 80