apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  template:
    spec:
      volumes:
      - name: creds
        secret:
          secretName: akeyless-cf-argocd
          items:
            - key: cf-argocd
              path: credentials.json