apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
spec:
  project: default
  source:
    repoURL: https://github.com/honahuku/manifest.git
    targetRevision: main
    path: applications/overlays/$(ENV)
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
