apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-settings
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/honahuku/manifest.git
    targetRevision: main
    path: argocd-settings/overlays/$(ENV)
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
