apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
spec:
  project: system
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: argocd
    repoURL: https://github.com/honahuku/manifest
    targetRevision: master