apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/honahuku/manifest.git
    targetRevision: main
    path: argocd/overlays/$(ENV)
  destination:
    server: https://kubernetes.default.svc
