apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
spec:
  project: default
  source:
    repoURL: https://helm.cilium.io/
    targetRevision: 1.17.6
    chart: cilium
    helm:
      valuesObject:
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
