apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connect
  namespace: connect
  source:
    repoURL: "https://1password.github.io/connect-helm-charts/"
    targetRevision: HEAD
    chart: connect
    helm:
      parameters:
        - name: operator.create
          value: "true"
        - name: operator.token.value
          value: OP_CONNECT_TOKEN
  destination:
    server: https://kubernetes.default.svc
    namespace: connect
