apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: connect
  namespace: connect
spec:
  project: default
  source:
    chart: connect
    repoURL: https://1password.github.io/connect-helm-charts/
    targetRevision: 1.14.0
    helm:
      valuesObject:
        operator:
          create: true
  destination:
    server: https://kubernetes.default.svc
    namespace: connect
