apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
spec:
  project: default
  source:
    repoURL: https://charts.longhorn.io/
    targetRevision: v1.8.0
    chart: longhorn
    helm:
      valuesObject:
        preUpgradeChecker:
          jobEnabled: false
        persistence:
          # シングルノード向け設定
          # https://github.com/longhorn/longhorn/discussions/5737
          # https://longhorn.io/docs/archives/1.4.1/references/settings/#default-replica-count
          defaultClassReplicaCount: 1
        defaultSettings:
          # node 単位で replica が分かれる設定を無効化する(多分そう)
          # https://longhorn.io/docs/archives/1.4.1/references/settings/#replica-node-level-soft-anti-affinity
          replicaSoftAntiAffinity: true
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
