apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://nextcloud.github.io/helm/
    chart: nextcloud
    targetRevision: 6.6.3
    helm:
      values: |
        nextcloud:
          host: nextcloud.honahuku.dev
        persistence:
          enabled: true
        metrics:
          https: true
        phpClientHttpsFix:
          enabled: true
        hpa:
          enabled: true
          minPods: 2
          maxPods: 10
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
