apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-db
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.7.20
    chart: postgresql
    helm:
      valuesObject:
        global:
          imageRegistry: mirror.gcr.io
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
