apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud-db
spec:
  project: default
  source:
    # bitnami は OCI 形式に変更されたらしい https://github.com/helm/helm/issues/13466
    # argocd で repourl を書くときは OCI: を付けなくていい https://argo-cd.readthedocs.io/en/stable/user-guide/helm/#declarative
    repoURL: registry-1.docker.io/bitnamicharts
    targetRevision: 16.7.20
    chart: postgresql
    helm:
      valuesObject:
  destination:
    server: https://kubernetes.default.svc
    namespace: nextcloud
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
