apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  annotations:
    link.argocd.argoproj.io/external-link: http://192.168.30.73:31080/
spec:
  project: default
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  source:
    path: nginx/overlays/production
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true