apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: kubeshark-worker-daemon-set
    app.kubernetes.io/instance: kubeshark
    kubeshark-created-by: kubeshark
    kubeshark-managed-by: kubeshark
  name: kubeshark-worker-daemon-set
  namespace: kubeshark
$patch: delete
