apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
spec:
  source:
    helm:
      valuesObject:
        replicaCount: 2
        nextcloud:
          host: nextcloud.honahuku.dev
        persistence:
          enabled: true
        metrics:
          https: false
        # phpClientHttpsFix:
        #   enabled: false
        service:
          type: NodePort
          nodePort: 30000
        internalDatabase:
          enabled: false
        externalDatabase:
          type: postgresql
          host: nextcloud-db
          user: postgres
          existingSecret:
            enabled: true
            secretName: nextcloud-db-postgresql
            passwordKey: postgres-password
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
