apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared
spec:
  template:
    spec:
      volumes:
      - name: creds
        secret:
          secretName: url-redirector-tunnel-credentials