resources:
  - ../../template/cloudflared
  - extsec-cf-url-redirector.yaml

patches:
  - path: deployment.yaml

configMapGenerator:
  - name: cloudflared
    files:
    - config.yaml

namePrefix: url-redirector-