apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose-linux-amd64 convert -f compose.yaml
    kompose.version: 1.35.0 (9532ceef3)
  labels:
    io.kompose.service: nextcloud-aio-mastercontainer
  name: nextcloud-aio-mastercontainer
spec:
  ports:
    - name: "80"
      port: 80
      targetPort: 80
    - name: "8080"
      port: 8080
      targetPort: 8080
    - name: "8443"
      port: 8443
      targetPort: 8443
  selector:
    io.kompose.service: nextcloud-aio-mastercontainer
