apiVersion: argoproj.io/v1alpha1
kind: Application
namespace: argocd
metadata:
  name: argo-cd
spec:
  project: system
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: argocd/overlays/production
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  syncPolicy:
    automated:
      # リソース自動削除。trueならmanifestに存在しないリソースは削除される
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true