apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  project: default
  destination:
    namespace: httpbin
    server: https://kubernetes.default.svc
  source:
    path: httpbin
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true