apiVersion: argoproj.io/v1alpha1
kind: Application
namespace: argocd
metadata:
  name: application
spec:
  project: system
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: root
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main