tunnel: argowf
credentials-file: /etc/cloudflared/creds/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true
ingress:
- hostname: argowf.honahuku.com
  service: https://argo-server.argowf:2746
  originRequest:
    noTLSVerify: true
- service: http_status:404