# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

labels:
  - includeSelectors: true
    pairs:
      env: development

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      - url=https://argocd-stg.honahuku.dev
      # stg か prd かを ArgoCD の WEB UI のバナーに表示するやつ
      # https://argo-cd.readthedocs.io/en/stable/operator-manual/custom-styles/#banners
      - ui.bannercontent="ここはステージング環境です"
      - ui.bannerpermanent="true"
      - ui.bannerposition="top"
