# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-local/all.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datadog

resources:
  - 1password-item.yaml
  - datadog-agent.yaml
  - namespace.yaml

helmCharts:
  - name: datadog
    namespace: datadog
    includeCRDs: false
    releaseName: datadog
    version: 3.49.7
    repo: https://helm.datadoghq.com
  - name: datadog-crds
    namespace: datadog
    includeCRDs: true
    valuesInline:
      crds:
        datadogAgents: true
    releaseName: datadog
    version: 1.3.0
    repo: https://helm.datadoghq.com
