# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-local/all.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: datadog

resources:
  - namespace.yaml

helmCharts:
  - name: datadog
    namespace: datadog
    includeCRDs: false
    valuesInline:
      operator:
        create: true
      connect:
        replicas: 3
    releaseName: datadog
    version: 3.49.7
    repo: https://helm.datadoghq.com
