# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-local/all.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx

resources:
  - namespace.yaml

helmCharts:
  - name: ingress-nginx
    namespace: ingress-nginx
    includeCRDs: false
    # valuesInline:
    #   operator:
    #     create: true
    releaseName: ingress-nginx
    version: 4.8.3
    repo: https://kubernetes.github.io/ingress-nginx
