apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets

helmCharts:
- name: external-secrets
  includeCRDs: true
  releaseName: external-secrets
  version: 0.8.1
  repo: https://charts.external-secrets.io

resources:
- externalsecret/
- secretstore/