apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-deployment
  labels:
    app: cloudflared
    app.kubernetes.io/component: server
    app.kubernetes.io/version: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-service
      pod: cloudflared
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-service
        pod: cloudflared
    spec:
      containers:
      - command:
        - cloudflared
        - tunnel
        # In a k8s environment, the metrics server needs to listen outside the pod it runs on.
        # The address 0.0.0.0:2000 allows any pod in the namespace.
        - --metrics
        - 0.0.0.0:2000
        - run
        args:
        - --token
        # TODO: tokenをGitHubから読み出す
        - <token value>
        image: cloudflare/cloudflared:latest
        name: cloudflared
        livenessProbe:
          httpGet:
          # Cloudflared has a /ready endpoint which returns 200 if and only if
          # it has an active connection to the edge.
            path: /ready
            port: 2000
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
status: {}