# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-local/all.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cloudflared
resources:
  - deployment.yaml
  - namespace.yaml

labels:
  - includeSelectors: true
    pairs:
      env: production

configMapGenerator:
  - name: cloudflared
    files:
      - config.yaml=cloudflared-config.yaml
  - name: argocd-cmd-params-cm
    behavior: merge
    literals:
      - server.insecure=true
