apiVersion: apps/v1
kind: Deployment
metadata:
  name: terraria-deployment
  labels:
    app: terraria
    app.kubernetes.io/component: server
    app.kubernetes.io/version: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: terraria-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: terraria-service
    spec:
      containers:
        - name: httpbin
          image: kennethreitz/httpbin:latest
          ports:
            - containerPort: 80
