apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
    app.kubernetes.io/component: server
    app.kubernetes.io/version: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-service
  strategy: {}
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        resources: {}
status: {}