apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nginx

resources:
- namespace.yaml
- deployment.yaml
- service.yaml
- cloudflared-configmap.yaml
- cloudflared-deployment.yaml