apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-redirector-deployment
  labels:
    app: url-redirector
    app.kubernetes.io/component: server
    app.kubernetes.io/version: latest
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: url-redirector-svc
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: url-redirector-svc
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: conf
          mountPath: /etc/nginx/conf.d/
          readOnly: true
      volumes:
      # nginx.confからconfigmapを生成する
      - name: config
        configMap:
          name: url-redirector
          items:
          - key: config.yaml
            path: config.yaml
status: {}