apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: system
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: argocd/base
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  syncPolicy:
    automated:
      # リソース自動削除。trueならmanifestに存在しないリソースは削除される
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-apps
  namespace: argocd
spec:
  project: system
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: cloudflared-apps
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  project: default
  destination:
    namespace: httpbin
    server: https://kubernetes.default.svc
  source:
    path: httpbin
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: url-redirector
  namespace: argocd
spec:
  project: default
  destination:
    namespace: url-redirector
    server: https://kubernetes.default.svc
  source:
    path: url-redirector
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argowf
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argowf
    server: https://kubernetes.default.svc
  source:
    path: argowf/base
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraria
  namespace: argocd
spec:
  project: default
  destination:
    namespace: terraria
    server: https://kubernetes.default.svc
  source:
    path: terraria/base
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.4.1
    helm:
      releaseName: longhorn
  destination:
    server: "https://kubernetes.default.svc"
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    path: external-secrets
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  destination:
    namespace: external-secrets
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: akeyless-gw
  namespace: argocd
spec:
  project: default
  source:
    chart: akeyless
    repoURL: https://akeylesslabs.github.io/helm-charts
    targetRevision: 1.26.4
    helm:
      releaseName: akeyless-api-gateway
  destination:
    server: "https://kubernetes.default.svc"
    namespace: akeyless
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helmapps-config
  namespace: argocd
spec:
  project: default
  source:
    path: helmapps-config
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true