apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
spec:
  project: system
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: argocd/base
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  syncPolicy:
    automated:
      # リソース自動削除。trueならmanifestに存在しないリソースは削除される
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-apps
  namespace: argocd
spec:
  project: system
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: cloudflared-apps
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: httpbin
  namespace: argocd
spec:
  project: default
  destination:
    namespace: httpbin
    server: https://kubernetes.default.svc
  source:
    path: httpbin
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  source:
    path: nginx
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argowf
  namespace: argocd
spec:
  project: default
  destination:
    namespace: argowf
    server: https://kubernetes.default.svc
  source:
    path: argowf/base
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraria
  namespace: argocd
spec:
  project: default
  destination:
    namespace: terraria
    server: https://kubernetes.default.svc
  source:
    path: terraria
    repoURL: https://github.com/honahuku/manifest
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.3.3
    helm:
      releaseName: v1-longhorn
      # values: |
      #   mode: standalone
      #   replicas: 1
      #   persistence:
      #     size: 5Gi
      #   DeploymentUpdate:
      #     type: Recreate
      #   resources:
      #     requests:
      #       memory: 1Gi
      #   metrics:
      #     serviceMonitor:
      #       enabled: true
      #       additionalLabels:
      #         release: prometheus
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn
  syncPolicy:
    automated:
      prune: true
      selfHeal: true