apiVersion: v1
kind: Namespace
metadata:
  name: argocd
---
apiVersion: v1
kind: Namespace
metadata:
  name: cloudflared
---
apiVersion: v1
kind: Namespace
metadata:
  name: httpbin
---
apiVersion: v1
kind: Namespace
metadata:
  name: url-redirector
---
apiVersion: v1
kind: Namespace
metadata:
  name: argowf
---
apiVersion: v1
kind: Namespace
metadata:
  name: terraria
---
apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: external-secrets
---
apiVersion: v1
kind: Namespace
metadata:
  name: akeyless
---
apiVersion: v1
kind: Namespace
metadata:
  name: datadog