apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: extsec
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-secret-store # Must match SecretStore on the cluster