apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:OU0Ts+Sks8a2BpMLtZuZiIsO4YqYqxFwFk9FSS51Si+LjYGPX/GJ3LRMJ2sFPRi6uyTEqrRRik8ziFJMo0sF3ThaxokZLcQTGPgE/zv/inHV2rnoAIQec4KNAUiHD8fmVZqftOtf8IoXIozJX3hkWROjBVHpWVSx7DWTLbvKfnNgx0MT44QciQQ0yKp7Aufb4uhJHA1zlaH5q40cmzr7y8vHRpl+ZI7/hmaVr9GzHFp0xM40VDIOSDoPpVB1jEDTPUUxGD+D2btJn9RT7AcYWC6XmuwCiBDM,iv:YDQcnbfKNQ9FIeYJFrmw6R8rsOhTgQmqZjgrXE1NzpA=,tag:SKMBsp5TkOSpYpsNfGY5Aw==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: argocd-tunnel-credentials
    namespace: cloudflared
    annotations:
        kustomize.config.k8s.io/behavior: merge
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d6wnr2tm2sp7z57l4n8l22d8l89majkpyddknkcvrufukv2l39wsgg887u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFMCtXTy9MM09yUmg4Vmdu
            alJBWmc4YXgyZ28vZXBkV2J6TnB0cFlMNkNnCmlLL0JhaHVuYngwL29YTWM5c0c3
            dzVPa3JYTUVGWHlFV0pQeEppY0Q4eFEKLS0tIDNKTjZ1NzRlV2VtdWN6RWx4b21s
            NnlTdkxlSlpJblJBRGNFWmJCRzZabXcKegupD0WodRsWMamMKEYHbkNRbvfLtCyi
            6ZiU1EFclg1Sm+yIxxC0AGRWv/Un3hVedPiPtE1v+aWZfGSeZQeUUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-11T16:33:21Z"
    mac: ENC[AES256_GCM,data:8+Q1aOP4bA+YQS7LZdnSqz1xiV91/ybDeSr+t0NNv72t/lXaMVcXviI3MqLIXda5+IvHGZBfgu7asnXMXMmPj6Rpgl5oxHCN7y2Q/OXzO7R4FvBeBnkHSSYbJnhOC7ybJgdx0asWCoCYvjibHNA1I4fAHRjDCV0HNutgx75R03Q=,iv:jOpUlFKxUyfcSNzXds8/8YC5Wf3aGjOcPva8Pm6Z5CE=,tag:ZCZFYw3XjbAK8yE6CGGxJg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
