apiVersion: v1
kind: Secret
metadata:
    name: argocd-tunnel-credentials
    namespace: cloudflared
data:
    credentials.json: eyJBY2NvdW50VGFnIjoiYmQ2ZGIxZmY0MGExYWY5MzQ3YmM1ZjE5MWFjOTI1ZWEiLCJUdW5uZWxTZWNyZXQiOiJseFBJNlRVTnhEeDFOSzZ6dTBXOTI4aE5kaUhlL3cwQjE0YzcrZlhySm1vPSIsIlR1bm5lbElEIjoiODA1YjZiMTEtYWViZC00Mzc3LThhMDEtNWUxNDY3ZDUwOGQ4In0=
