# yaml-language-server: $schema=https://json.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/

labels:
  - includeSelectors: true
    pairs:
      env: production

configMapGenerator:
  - name: argocd-cm
    behavior: merge
    literals:
      # SSO を構成する際に使う ArgoCD の外部アドレス
      # ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/argocd-cm-yaml/
      - url=https://argocd.honahuku.dev
      # stg か prd かを ArgoCD の WEB UI のバナーに表示するやつ
      # ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/custom-styles/#banners
      - ui.bannercontent="ここは本番環境です"
      - ui.bannerpermanent="true"
      - ui.bannerposition="top"
