apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloudflared-apps
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/honahuku/manifest
        revision: main
        directories:
          - path: cloudflared-apps/*
  template:
    metadata:
      name: "cloudflared-apps-{{path.basenameNormalized}}"
      namespace: argocd
    spec:
      project: cloudflared-apps
      source:
        repoURL: https://github.com/honahuku/manifest
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "cloudflared"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
        # retry:
        #   limit: -1
        #   backoff:
        #     duration: 5s
        #     factor: 2
        #     maxDuration: 2m