apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared-apps
spec:
  project: system
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    path: cloudflared-apps
    repoURL: https://github.com/honahuku/manifest
    targetRevision: add/cloudflare-tunnel