apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
spec:
  source:
    helm:
      valuesObject:
        nextcloud:
          host: nextcloud-stg.honahuku.dev
        persistence:
          enabled: true
        metrics:
          https: true
        phpClientHttpsFix:
          enabled: true
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
