apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nextcloud
spec:
  source:
    helm:
      valuesObject:
        # # https://github.com/nextcloud/helm/tree/main/charts/nextcloud#database-configurations
        # internalDatabase:
        #   enabled: false
        # externalDatabase:
        #   enabled: true
        #   type: mysql
        nextcloud:
          host: nextcloud-stg.honahuku.dev
        persistence:
          enabled: true
        metrics:
          https: true
        phpClientHttpsFix:
          enabled: true
