name: renovate(dry-run)

on:
  pull_request:
    paths:
      - '.github/renovate.json'
      - '.github/workflows/renovate*.yml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate Renovate Config
        run: |
          set -eux
          npx --yes --package renovate -- renovate-config-validator --strict
    if: github.event_name == 'pull_request'

  full:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:39.168
    env:
      RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
      RENOVATE_DRY_RUN: full
    steps:
      - uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.12
    if: github.event_name == 'pull_request'

  extract:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/renovatebot/renovate:39.168
    env:
      RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
      RENOVATE_DRY_RUN: extract
    steps:
      - uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.12
    if: github.event_name == 'pull_request'
