name: renovate

on:
  schedule:
    - cron: '0 8 * * 2,5'
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  renovate:
    runs-on: ubuntu-latest
    env:
      RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.13
        with:
          configurationFile: '.github/renovate.json'
          token: ${{ secrets.RENOVATE_TOKEN }}
