name: renovate

on:
  schedule:
    - cron: '0 8 * * 2,5'
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    container:
      image: renovate/renovate
    env:
      RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Run Renovate
        run: >
          renovate --platform gitlab \
          --allow-command-templating true
