apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:bSU03A4eEgB1VOxA0TeUurpvrHLRZk1K2e/3YZgaBAzljj7IlloykZ8/sZe8RexI6qOG0nYOxMx8190eAa6KWTwqM6EEGu+lpZ90ywEKfRWyzOx9tJuxlLn8uhd3C2RophTixhqALZuOtciC6A+k7IafcWSy47vDshp5C7GcXofo6g3T0oeidTM98jV7/6OO3up9swfQZW3rpB1tuHxs7h8xT93p7mwIk3Zv2RSLYul+9wTpIsyJbKhLPNtZDHg0IPv2Pvw4l5md4Y9oUqHvKiIwNx+V2jyv,iv:MKQkS6UjekHtx252Qio3oYfAGFSrggZOuU0WDZLA7jI=,tag:g2Yg7BkYvocYQTh+j617JA==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: argocd-tunnel-credentials
    namespace: cloudflared
    annotations:
        kustomize.config.k8s.io/behavior: merge
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d6wnr2tm2sp7z57l4n8l22d8l89majkpyddknkcvrufukv2l39wsgg887u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBUHI1Q0VKRjI3S3NYTHBS
            V2pYc1JFOXFTSVhRQWVyVUJxa3VCOTl3MWdZCkdoL2JFdEdWMzN0WDloR0dhWU5W
            dmhRSGdkYUV0SWdlZmx6N3J0SlFJUFEKLS0tIFJEdmpxQ3JwWkhqVUpJTVczendI
            d1k5YTZrMXBESVFkMVM2NCtVUEJ5RTQK82JJnB/+r2mIHbVSTISoVAan+eSuHLKX
            LJJyasZPPJHa2+Te0MbAOQIzO1qDk6AU3xFIlVTIJKy2ngTkFQ9eOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-11T16:36:32Z"
    mac: ENC[AES256_GCM,data:OgXNraDhGltbwGY6jyqhMSce4OwmfvrGo1EWuAm83uFupqPHDsiNY6LVS5CmHa/VVtAYw5EN9BPIiNj7b5kXYwxKqEnXHNz5d3ghp4OAtBL6Np/tccEa49u6TeG8yhFud1tfNvo37+B9eGPy06ECUPxLNc26exHjCtX9/Jt7F9c=,iv:XydYufdSpMH68mdJgWBuNf9TVwiYJs4a0PAZYCU8aQk=,tag:QAWMFMaCaKteWwdBLyppQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
