apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:KlZHBuZIKqiPf88PztzRhzi9IUyIcDfBE0SvG7XejuZaevmblJvyFtM+BswlfHN8nlEaSYpEVAJUq4I5ktBPhjzgRvzRgZTgAPzY7FBx3R67ox8gV1sU4MsyXm4HOi2jxtRDMs/tXoyXnUYj/VioiArs0LicFKlcc5qtoFfJrCT6yioKiqrAThGAX5iIR+GfSQlrq2Ynvg1t7j37eMWTf5epRfCO2Hf9ZwC81qo4jNS6AHIBuohc//XHyyktMfBBIpnJrpmlB2dlQYwd5bNoeMKxCvwydsGt,iv:QJiDaL72GsV+cxorBWX7pAnMGf0LFoDDMjOAC7JJQGE=,tag:w01blmHv9GCZ6wcEPqhcWQ==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: argocd-tunnel-credentials
    namespace: cloudflared
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1d6wnr2tm2sp7z57l4n8l22d8l89majkpyddknkcvrufukv2l39wsgg887u
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwVExldkZtWjFaVWhGMUYz
            c0RQNGpLdmVmNk1WLzBBSG9ibmlIR2Q5S1ZNCncyWHJ3U0RWM052ZGhRcDNralY2
            aWo1ZmxwU3FxYVJ3bXF2Z1NMRlhnR1EKLS0tIG83cnhpdHZ5MWkwa09wWTB1MG4z
            QWZYVVhvSVFtSjRoeFk2UXNidERJR1UKnUgS6iMKNlLj/y+PgmoT9NLHJ5Dy1hGa
            g2QGY6VXxBgNBwG+9W+bv0Otx7UtKEAdqfi19NKgXSmVrk4ZZGGCnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-02-11T15:50:29Z"
    mac: ENC[AES256_GCM,data:G/0gm+BlrBeLrHfRjKYsyQppGQGMzUuLpAvrEoU6/OzcRcGeGnfR0Hv5vGEpetTTF8wfJVYaVqUM4KDP+fQNCKhKAse2r/ak2B+R7xuYqRBHLuW9WnZmJC46GoB61Thb/U9Ogzpg2w8NFbq9u3ZZd10elXVC7NHxEO/cvD9D1Ow=,iv:+LGgiWgqBD6Xqbn31u/myxYDR0LhDVqy0bbjAPgOju8=,tag:vFHH//H59Q2ceI1wzzlCig==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.4
